[build]
  # Répertoire de publication
  publish = "build"
  
  # Commande de build
  command = "npm run build"

[build.environment]
  # Version de Node.js
  NODE_VERSION = "16"
  
  # Variables d'environnement pour le build
  REACT_APP_API_URL = "https://api.dropshop.com/api"
  GENERATE_SOURCEMAP = "false"

# Redirections pour React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://connect.facebook.net https://js.stripe.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.stripe.com https://www.google-analytics.com https://api.dropshop.com"

# Cache pour les assets statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pour les images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache pour les fonts
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuration pour les fonctions Netlify (si utilisées)
[functions]
  directory = "netlify/functions"

# Configuration des variables d'environnement par contexte
[context.production.environment]
  REACT_APP_API_URL = "https://api.dropshop.com/api"
  REACT_APP_STRIPE_PUBLISHABLE_KEY = "pk_live_your_live_key"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://staging-api.dropshop.com/api"
  REACT_APP_STRIPE_PUBLISHABLE_KEY = "pk_test_your_test_key"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://dev-api.dropshop.com/api"
  REACT_APP_STRIPE_PUBLISHABLE_KEY = "pk_test_your_test_key"
